### ISSUE TITLE
Support for linux and windows platforms

### ISSUE THREAD

**Issue by anjelo** [ecrmnn/minta#1]
It would be nice if the app can be run under windows or linux OSes just like other electron-based apps.

**Comment by ecrmnn** [comment]
Have you tried to build and run it on Win or Linux?
I havn't tested it myself, but . PRs are much appreciated 😄

**Comment by ecrmnn** [comment]
That'd be great. I havn't tried to build and run on Win or Linux.
If you have the chance to test it out, please do.
If any changes are necessary to make it work, PRs are welcome 😄
