### ISSUE TITLE
Add Windows build

### ISSUE THREAD

**Issue by edmael** [ecrmnn/minta#10]
Hey, I saw that you merged a PR about adding Windows support.

Is there a way I can help to release a Windows build so that anyone can download it?

Thanks.

**Comment by ecrmnn** [comment]
Yes!

I'd want to add you as a collaborator, but the permission customization on personal repos kinda sucks.

Maybe a bit cumbersome; But if you could build it based on version 1.0.2 (master) and email me the executable. See package.json for email.

**Comment by edmael** [comment]
May I ask you for some directions?
Shall I just compile with "npm install" and send you the exe?
I'm kind of new with electron.

**Comment by ecrmnn** [comment]
Sure!
Here is a quick guide. Just tell me if you're stuck or anything.

```bash
# Clone the repo
git clone https://github.com/ecrmnn/minta.git

# Go into the project
cd minta

# Install dependencies
npm install

# Test run the app before building
# - You can then quit by exiting the app window or ctrl+c in the terminal I think
npm start

# Build the app
npm run build:win

# The .exe will be found in dist/win directory
```

**Comment by edmael** [comment]
I'm sending you just the .exe (as soon as I manage to upload it with my aweful connection), if you need all the other file in that folder just ask.

Have a nice day!

**Comment by mokhosh** [comment]
@edmael did you manage? :D

**Comment by edmael** [comment]
@safir187 I have a build that works on my PC, but for some reason when I compile the .exe I get an unusable blob.

I'm investigating this with @ecrmnn to try and publish it asap.

**Comment by ecrmnn** [comment]
Closed due to inactivity
