### ISSUE TITLE
Feature Request: Save Regex's or Import previous ones?

### ISSUE THREAD

**Issue by jkupczak** [ecrmnn/minta#4]
Would it be possible to save a regex (and the strings used to create it) for use at a later date? Say for instance I create a long and complicated regex. But weeks later I want to add to it. I'm not sure there's a way to do that right now? Alternatively, if I could feed Minta a regex and it populates the matchable strings that would be great too.

**Comment by ecrmnn** [comment]
Both great ideas! PRs are welcome so please feel free to submit 😄
