### ISSUE TITLE
Options to avoid percent-encording

### ISSUE THREAD

**Issue by revi** [ecrmnn/minta#8]
Hi!

Currently it looks like app is loading non-latin languages in percent-encording, but since I'm native speaker of non-latin languages, this is kinda annoying. Can it be configured to not show percent-encording?

<img width="437" alt="minta_2018-01-24 17-54-14 2x" src="https://user-images.githubusercontent.com/7630875/35323105-c69ef74c-012f-11e8-9b0a-bc9013662679.png">

Thanks!

**Comment by saidsay-so** [comment]
Actually, that's not percent-encoding but unicode hexadecimal. ([Unicode reference](http://www.fileformat.info/info/unicode/char/ac00/index.htm)) However, the "[problem](https://github.com/devongovett/regexgen#es2015-and-unicode)" seems to be with the library itself.

**Comment by saidsay-so** [comment]
This seems to works. (I just tested with a random sentence so don't blame me...)

![image](https://user-images.githubusercontent.com/12956751/35349964-bcabb8a8-013c-11e8-997a-3b7477ad7b00.png)

**Comment by ecrmnn** [comment]
Off topic, but maybe the "Minta title" should be hidden on Windows. That does not look good with two "titles".

**Comment by saidsay-so** [comment]
But I'm on Linux Mint 🤣  !

**Comment by ecrmnn** [comment]
Hah! I thought that was Windows. Been too long since I touched something other than OS X/MacOS I guess... 😂

**Comment by saidsay-so** [comment]
😂😂😂
